language: node_js
node_js:
- '12.16'
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: lBqggOehG/YpJyjh4ibO+XHC6srueAxsFbHGVVV1yUpmy2Dl11BKaI02w7sPAn6c8HRDMrJ4NdS4FIIPVn/WXpTFHwDJ0B18X2oFOGgpQwN+Y2xENMZPxmtcmfdEFNbdSl1j0ilJSu8DPEG/1OHm1ZSRSuhFar72liEHRIzh2ghVUCRW2YbR15+AjTZKb+oPQwwuDJCon+vpusJS62brE2YFoaV0Hr46/20x7Zitq5XqAq7iXpmeOOTq9jbqJZlQHNRKj0XbOmd3BcNiwpvs4Sj38iPvhvB90JjoHC7UVya5td4Up2HMm8ZdfKSLmRVWKXYhMgr+k1NSLoRFXEgYd7E+Kkt3LgiMeSMVUE6XxqrnE+lSEa+XoFkDt8H8R02Rzy5B7qz3FJoc0M66xdyJx3lYjhHjfQl4NVE6RoXyoipCpKyf8gyEqXuVqdkL1tnpethT6uGUOq4uv0PFqMP8xNQkbXs+dTV8prHbjVW5Zd5hp29UX0jaNlepYgrRMY1qVVRVhkcL89WuDnYu5PtpPz1qYwEChsyh2DeeVB7lbfSIYCSKo29sVq4ugxGXyLFL0lw1J6nlSmHHMeFRF0yMkWOaN9KxCOswy5aqU2EfqrEuBNSk2tu9fOm+PN2AbI5HdjPpoAjp/lesPAJViGTSZIbcfwxbw+2xXzzJRfr10eE=
  on:
    tags: true
    repo: Mael-91/Components
  skip_cleanup: 'true'
