language: node_js

node_js:
  - "12.16"

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: demo
    on:
      branch: master